***@Author: Ranjith G C***
<br>
***@Date: 2021-07-12***
<br>
***@Last Modified by: Ranjith G C***
<br>
***@Last Modified time: 2021-07-12*** 
<br>
***@Title : Program Aim to change the datatype of an array.***

In [1]:
import numpy as np
from loggers import logger
try:
    arr = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
    print(arr)
    print("Data type of the array x is:", arr.dtype)
    # Change the data type of x
    arr1 = arr.astype(float)
    print("New Type: ", arr1.dtype)
    print(arr1)
except Exception as e:
    logger.error(e)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
