In [ ]:
"""
@Author: Ranjith G C
@Date: 2021-07-12
@Last Modified by: Ranjith G C
@Last Modified time: 2021-07-12 
@Title : Program Aim is to create a 8x8 matrix and fill it with a checkerboard pattern. Go to the editor
         Checkerboard pattern:
"""

In [1]:
import numpy as np
from loggers import logger
try:
    print("Checkerboard pattern:")
    arr6 = np.zeros((8,8),dtype=int)
    arr6[1::2,::2] = 1
    arr6[::2,1::2] = 1
    print(arr6)
except Exception as e:
    logger.error(e)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
