***@Author: Ranjith G C***
<br>
***@Date: 2021-07-12***
<br>
***@Last Modified by: Ranjith G C***
<br>
***@Last Modified time: 2021-07-12*** 
<br>
***@Title : Program Aim to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.***

In [1]:
import numpy as np
from loggers import logger
try:
    arr = np.arange(12).reshape(3, 4)
    print("Original array elements:")
    print(arr)
    for i in np.nditer(arr, op_flags=['readwrite']):
        i[...] = 3 * i
    print("New array elements:")
    print(arr)
except Exception as e:
    logger.error(e)

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
