   Write a Python program to convert a list of numeric value into a one-dimensional
   NumPy array.

In [2]:
import numpy as np
list = [1,2,3,4,5]
print("Original List:", list)
arr = np.array(list)
print("One-dimensional NumPy Array:", arr)

Original List: [1, 2, 3, 4, 5]
One-dimensional NumPy Array: [1 2 3 4 5]


 Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
import numpy as np
l1 = [[2,3,4],[5,6,7],[8,9,10]]
print("Original array: ")
print(l1)
arr1 = np.array(l1)
print("2D Array 3*3 is: ", arr1)

Original array: 
[[2, 3, 4], [5, 6, 7], [8, 9, 10]]
2D Array 3*3 is:  [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [4]:
import numpy as np
arr2 = np.zeros(10)
print(arr2)
print("Updated sixth value is:")
arr2[6] = 11 
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated sixth value is:
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


Write a NumPy program to reverse an array (first element becomes last).

In [6]:
import numpy as np
arr3 = np.arange(1,20)
print("Original Array")
print(arr3)
print("Reversed Array")
arr3 = arr3[::-1]
print(arr3)

Original Array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reversed Array
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [7]:
import numpy as np
arr4 = np.ones((5,5))
print("Original Array: ")
print(arr4)
print("1 on the border and 0 inside the array: ")
arr4[1:-1, 1:-1] = 0
print(arr4)

Original Array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside the array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to add a border (filled with 0's) around an existing array

In [8]:
import numpy as np
arr5 = np.ones((3,3))
print("Original array:")
print(arr5)
print("0 on the border and 1 inside in the array")
arr5 = np.pad(arr5, pad_width=1, mode='constant', constant_values=0)
print(arr5)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. Go to the editor
Checkerboard pattern:

In [9]:
import numpy as np
arr6 = np.ones((3,3))
print("Checkerboard pattern:")
arr6 = np.zeros((8,8),dtype=int)
arr6[1::2,::2] = 1
arr6[::2,1::2] = 1
print(arr6)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Write a NumPy program to convert a list and tuple into arrays. 

In [10]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
arr7 = np.asarray(my_list)
print(arr7)
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
arr8 = np.asarray(my_tuple)
print(arr8)

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


Write a NumPy program to append values to the end of an array.

In [11]:
import numpy as np
list = [1, 2, 3]
print("Original Array: ")
print(list)
arr9 = np.append(list, [[4,5,6],[7,8,9]])
print("After Append Values are")
print(arr9)

Original Array: 
[1, 2, 3]
After Append Values are
[1 2 3 4 5 6 7 8 9]


Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [12]:
import numpy as np
a = np.sqrt(1+0j)
b = np.sqrt(0+1j)
print("Original Array a:", a)
print("Original b:", b)
print("Real Part of Array:")
print(a.real)
print(b.real)
print("Imaginary Part of Array:")
print(a.imag)
print(b.imag)

Original Array a: (1+0j)
Original b: (0.7071067811865476+0.7071067811865476j)
Real Part of Array:
1.0
0.7071067811865476
Imaginary Part of Array:
0.0
0.7071067811865476


Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [13]:
import numpy as np
x = np.array([1,2,3], dtype=np.float64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


Write a NumPy program to find common values between two arrays.

In [14]:
import numpy as np
arr1 = np.array([0, 10, 20, 30, 40, 50])
print("Array1:", arr1)
arr2 = [10, 30, 50]
print("Array2:", arr2)
print("Common Values between 2 Arrays are:", np.intersect1d(arr1, arr2))

Array1: [ 0 10 20 30 40 50]
Array2: [10, 30, 50]
Common Values between 2 Arrays are: [10 30 50]


Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. 

In [15]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [16]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


Write a NumPy program compare two given arrays.

In [17]:
import numpy as np
arr1 = np.array([1, 3, 7])
arr2 = np.array([4, 5, 6])
print("Array a: ",arr1)
print("Array b: ",arr2)
print("arr1 > arr2")
print(np.greater(arr1, arr2))
print("arr1 >= arr2")
print(np.greater_equal(arr1, arr2))
print("arr1 < arr2")
print(np.less(arr1, arr2))
print("arr1 <= arr2")
print(np.less_equal(arr1, arr2))

Array a:  [1 3 7]
Array b:  [4 5 6]
arr1 > arr2
[False False  True]
arr1 >= arr2
[False False  True]
arr1 < arr2
[ True  True False]
arr1 <= arr2
[ True  True False]


Write a NumPy program to save a NumPy array to a text file.

In [18]:
import numpy as np
arr = np.arange(1.0, 2.0, 3.0)
np.savetxt('file.out', arr, delimiter=',')

Write a NumPy program to create a contiguous flattened array. 

In [19]:
import numpy as np
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:")
print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


Write a NumPy program to change the data type of an array.

In [20]:
import numpy as np
arr = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(arr)
print("Data type of the array x is:", arr.dtype)
# Change the data type of x
arr1 = arr.astype(float)
print("New Type: ", arr1.dtype)
print(arr1)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere

In [21]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to create an array which looks like below array. 

In [22]:
import numpy as np
arr = np.tri(4, 3, -1)
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


Write a NumPy program to concatenate two 2-dimensional arrays. 

In [23]:
import numpy as np
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
arr3 = np.concatenate((arr1, arr2), 1)
print(arr3)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


Write a NumPy program to make an array immutable (read-only).

In [24]:
import numpy as np 
arr = np.zeros(10)
arr.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
arr[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [25]:
import numpy as np
arr = np.arange(12).reshape(3, 4)
print("Original array elements:")
print(arr)
for i in np.nditer(arr, op_flags=['readwrite']):
    i[...] = 3 * i
print("New array elements:")
print(arr)

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


Write a NumPy program to convert a NumPy array into Python list structure.

In [26]:
import numpy as np
arr = np.arange(6).reshape(3, 2)
print("Original array elements:")
print(arr)
print("Array to list:")
print(arr.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


Write a NumPy program to display NumPy array elements of floating values with given precision.

In [27]:
import numpy as np
arr =np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
print("Original array elements:")
print(arr)
print("Print array values with precision 3:")
np.set_printoptions(precision=3)
print(arr)

Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


Write a NumPy program to suppresses the use of scientific notation for small numbers in NumPy array.

In [28]:
import numpy as np 
arr =np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01]) 
print("Original array elements:")
print(arr)
print("Print array values with precision 3:")
np.set_printoptions(suppress=True)
print(arr)

Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


Write a NumPy program to add an extra column to a NumPy array.

In [29]:
import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]
