In [ ]:
"""
@Author: Ranjith G C
@Date: 2021-07-12
@Last Modified by: Ranjith G C
@Last Modified time: 2021-07-12 
@Title : Program Aim is to add a border (filled with 0's) around an existing array.
"""

In [1]:
import numpy as np
from loggers import logger
try:
    arr5 = np.ones((3,3))
    print("Original array:")
    print(arr5)
    print("0 on the border and 1 inside in the array")
    arr5 = np.pad(arr5, pad_width=1, mode='constant', constant_values=0)
    print(arr5)
except Exception as e:
    logger.error(e)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
