***@Author: Ranjith G C***
<br>
***@Date: 2021-07-12***
<br>
***@Last Modified by: Ranjith G C***
<br>
***@Last Modified time: 2021-07-12*** 
<br>
***@Title : Program Aim to create an array which looks like below array.***

In [1]:
import numpy as np
from loggers import logger
try:
    arr = np.tri(4, 3, -1)
    print(arr)
except Exception as e:
    logger.error(e)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
