In [ ]:
"""
@Author: Ranjith G C
@Date: 2021-07-12
@Last Modified by: Ranjith G C
@Last Modified time: 2021-07-12 
@Title : Program Aim is to create a 2d array with 1 on the border and 0 inside.
"""

In [1]:
import numpy as np
from loggers import logger
try:
    arr4 = np.ones((5,5))
    print("Original Array: ")
    print(arr4)
    print("1 on the border and 0 inside the array: ")
    arr4[1:-1, 1:-1] = 0
    print(arr4)
except Exception as e:
    logger.error(e)

Original Array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside the array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
