***@Author: Ranjith G C***
<br>
***@Date: 2021-07-12***
<br>
***@Last Modified by: Ranjith G C***
<br>
***@Last Modified time: 2021-07-12*** 
<br>
***@Title : Program Aim is to convert a list and tuple into array.***

In [1]:
import numpy as np
from loggers import logger
try:
    my_list = [1, 2, 3, 4, 5, 6, 7, 8]
    print("List to array: ")
    arr7 = np.asarray(my_list)
    print(arr7)
    my_tuple = ([8, 4, 6], [1, 2, 3])
    print("Tuple to array: ")
    arr8 = np.asarray(my_tuple)
    print(arr8)
except Exception as e:
    logger.error(e)

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]
